//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_ice_attack.html
halflife.wad
cs_dust.wad
de_piranesi.wad
cs_assault.wad
cs_office.wad
itsitaly.wad
cs_havana.wad
prodigy.wad
maps/zm_ice_attack.bsp
