//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_toxic_house.html
halflife.wad
cstrike.wad
de_piranesi.wad
chateau.wad
cs_bdog.wad
torntextures.wad
maps/zm_toxic_house.bsp
maps/zm_toxic_house.txt
